NAME	:= philo
CC	:= cc
CFLAGS	:= -Wall -Wextra -Werror
RM	:= rm -rf
SRC	:= main.c init.c monitor.c routine.c time.c parser.c utils.c 
OBJ	:= $(SRC:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)

clean:
	$(RM) $(OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re
